### PR TITLE
Replace main page carousel

### PR DESCRIPTION
**Pull request by sprestrelski**
https://github.com/acmucsd/acm-ai-site/assets/33042752/9f79da82-0c23-4ef5-aceb-fc662b7f8eb5

### CODE REVIEW

**Comment by mohakvni** [comment]
The changes look good, although can you make all button colors the same to ensure uniformity? One if dark-button, the other two light-button.

**Review by mohakvni — CHANGES_REQUESTED** [review]
Button Change (comment left)

**Comment by sprestrelski** [comment]
New look 😼 
image

**Review by mohakvni — APPROVED** [review]
LGTM

**Pull request merged**
